<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Home</title>
</head>
<body>
	<?php 
	#echo '<pre>';
	#print_r($this->view->dados);
	#echo '<pre>';
		foreach ($this->view->dados as $indice => $info){
			echo $info['titulo'].' - '. $info['descricao'];
			echo '<br>';



			//echo $valor.'<br/>';
		}
?>

</body>
</html>
