<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/css/estilo-pag-principal.css">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Niconne&family=Pacifico&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100;200;300;400;500;600;700&family=Poppins:wght@200;300&display=swap" rel="stylesheet"> 
	<input type="checkbox" name="menu" id="check"></head>

	<header>
		<label for="check">
			<ion-icon name="reorder-four-outline" id="sidebar_btn"></ion-icon>

		</label>
	<div class="left">
		<h3>Sistema <span>EDU</span></h3>
	</div>
	<div class="right">	
		<ul>
			<li class="dropdown">
				<a href="/painel" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					<div class="profile_img">	
						<div class="user-name">
							<p>Administrador</p>
							<span>Administrador</span>
						</div>
					</div>	
				</a>
				<ul class="dropdown-content"> 
					<li> <a href="#modalPerfil" class="drop"><ion-icon name="person-outline"></ion-icon> Editar Perfil</a> </li>
					<li> <a href="#" class="drop"><ion-icon name="log-out-outline"></ion-icon> Sair</a> </li>
				</ul>
			</li>
		</ul>
	</div>
</div>

</header>
<div class="sidebar"> 
	<center>
		
		<img src="imagens/perfil.png" class="image" alt="">
		<h2>Admin</h2>
	</center>

	<a href="opcoes.html"><ion-icon name="person-add-outline"></ion-icon><span> Cadastrar</span></a>
	<!-- ######Mudança para o futuro
	<ul class="treeview-menu">
                  <li><a href="cad-turma.html"><i class="fa fa-angle-right"></i> Turma</a></li>
                  <li><a href="cad-disc.html"><i class="fa fa-angle-right"></i> Disciplina</a></li>
                  <li><a href="cad-estudante.html"><i class="fa fa-angle-right"></i> Estudante</a></li>
                  <li><a href="cad-prof.html"><i class="fa fa-angle-right"></i> Professor</a></li>
                </ul>
                -->
	<a href="#"><ion-icon name="people-outline"></ion-icon><span> Dados Pessoais</span></a>
	<a href="#"><ion-icon name="library-outline"></ion-icon><span> Dados Acadêmicos</span></a>
	<a href="#"><ion-icon name="settings-outline"></ion-icon><span> Configurações</span></a>


</div>
<div class="cont">



	
</div>

<!--<div class="modal" id="#modalPerfil" tabindex="-1" role="dialog"aria-labelledby="exampleModalLabel" aria-hidden="true">
      				<h2 class="modal-title" id="exampleModalLabel">Editar Dados</h2>
      				<button type="button" class="fechar" data-bs-dismiss="modal" aria-label="Close" style="margin-top: -20px" >
      					<span aria-hidden="true">&times;</span>
      				</button>
      			</div>

      			<form method="POST" class="formulario-recuperacao">
      							<label>Nome: </label>
      							<input type="text" name="nome_user" value="<?php echo $nome_user ?>" required>
      						</div>
      					</div>
      				</div>
      				<div class="col-md-6">
      					<div class="form-group">
      						<label>CPF: </label>
      						<input type="text"name="cpf_usu" value="<?php echo $cpf_usu ?>" required>
      					</div>
      				</div>

      				<div class="row">
      					<div class="col-md-6">
      						<div class="form-group">
      							<label>Email: </label>
      							<input type="email" name="email_usu" value="<?php echo $email_usu ?>" required>
      						</div>
      					</div>
      					<div class="col-md-6">
      						<div class="form-group">
      							<label>Senha: </label>
      							<input type="password" name="senha_usu" value="<?php echo $senha_usu ?>" required>
      						</div>
      					</div>
      				</div>
      				<div class="row">
      					<div class="col-md-8">
      						<div class="form-group">
      							<label>Foto: </label>
      							<input type="file" name="foto" onChange="carregarImg2();" id="foto_usu">
      						</div>
      					</div>
      					<div class="col-md-4">
      						<div class="divImg">
      							<img src="images/<?php echo $foto_usu ?>" width="100px" id="target-usu">
      						</div>
      					</div>
      				</div>
      				<input type="hidden" name="id_usu" value="<?php echo $id_usuario ?>">
      				<input type="hidden" name="foto_usu" value="<?php echo $foto_usu ?>">
      				<small>
      					<div id="msg-usu" align="center" class="mt-3"></div>
      				</small>

      			</form>
      		</div>
      		<div class="modal-footer">
      			<button type="submit" class="btn btn-primary">Editar Dados</button>
      		</div>
      	</div>
      </div>
    </div>
-->














<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<!--<script> /*quando clicar ele ativa o css que faz o quadro expandir*/
            let nav = document.querySelector('.modal')
            nav.onclick = function(){
                nav.classList.toggle('active')
            }
        </script>
-->

	</body>

</html>