<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Portal - Página Inicial</title>
	<link rel="stylesheet" type="text/css" href="estilo-pag-principal.css">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100;200;300;400;500;600;700&family=Poppins:wght@200;300&display=swap" rel="stylesheet">


</head>
<body>
	<input type="checkbox" name="menu" id="check">


	<header>
		<label for="check">
			<ion-icon name="reorder-four-outline" id="sidebar_btn"></ion-icon>

		</label>
	<div class="left">
		<h3>Sistema <span>EDU</span></h3>
	</div>
	<div class="right">	
		<ul>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					<div class="profile_img">	
						<div class="user-name">
							<p>Estudante</p>
							<span>Estudante</span>
						</div>
					</div>	
				</a>
				<ul class="dropdown-content"> 
					<li> <a href="#modalPerfil" class="drop"><ion-icon name="person-outline"></ion-icon> Editar Perfil</a> </li>
					<li> <a href="#" class="drop"><ion-icon name="log-out-outline"></ion-icon> Sair</a> </li>
				</ul>
			</li>
		</ul>
	</div>
</div>

</header>
<div class="sidebar"> 
	<center>
		
		<img src="imagens/perfil.png" class="image" alt="">
		<h2>Estudante</h2>
	</center>

	
	<a href="exib-atividades.html"><ion-icon name="library-outline"></ion-icon><span> Atividades</span></a>
	<a href="exib-notas.html"><ion-icon name="library-outline"></ion-icon><span> Notas</span></a>
	<a href="exib-disc.html"><ion-icon name="library-outline"></ion-icon><span> Disciplinas</span></a>
	<a href="exib-turma.html"><ion-icon name="library-outline"></ion-icon><span> Turmas do Estudante</span></a>



</div>
<div class="content">
	<div class="content-interna">
		<table id="customers">
  <tr>
    <th>Atividades </th>
    <th>Provas</th>
    <th>Disciplinas</th>
  </tr>
  <tr>
    <td> -- </td>
    <td> -- </td>
    <td> -- </td>
  </tr>
  <tr>
    <td> -- </td>
    <td> -- </td>
    <td> -- </td>
  </tr>
  <tr>
    <td> -- </td>
    <td> -- </td>
    <td> -- </td>
  </tr>
 <tr>
    <td> -- </td>
    <td> -- </td>
    <td> -- </td>
  </tr>
  <tr>
    <td> -- </td>
    <td> -- </td>
    <td> -- </td>
  </tr>
  <tr>
    <td> -- </td>
    <td> -- </td>
    <td> -- </td>
  </tr>
  <tr>
    <td> -- </td>
    <td> -- </td>
    <td> -- </td>
  </tr>
</table>

			
	</div>
	
</div>



<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>


</body>
</html>